[package]
name = "fallible"
version = "0.1.1"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Fallible operations"
license = "MIT OR Apache-2.0"

[dependencies]
void = { version = "1", default-features = false }
